backend:
  name: git-gateway

publish_mode: "editorial_workflow"
media_folder: "/static/images"
public_folder: "/images"

collections:
  - name: "bulletin"
    label: "Bulletin"
    folder: "content/bulletin"
    create: true
    slug: "bulletins-{{year}}-{{month}}-{{day}}"
    editor:
      preview: false
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "bulletin"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", timeFormat: false}
      - label: "Events"
        name: "events"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Date", name: "date", widget: "string"}
          - {label: "Time", name: "time", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Link", name: "link", widget: "string"}
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - label: "Church Information"
        name: "church"
        file: "/content/config/church.md"
        fields:
          - {label: "Type", name: "type", widget: "hidden", default: "church"}
          - {label: "Church name", name: "name", widget: "string"}
          - {label: "Welcome message", name: "message", widget: "text"}
          - {label: "Church Name", name: "name", widget: "string"}
          - label: "Call to action links"
            name: "cta"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "link", widget: "string"}
          - label: "Social media links"
            name: "links"
            widget: "list"
            fields:
              - label: "Link type"
                name: "type"
                widget: "select"
                options: ["Instagram", "Twitter", "YouTube", "Facebook", "Website"]
              - {label: "Link URL", name: "link", widget: "string"}